# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'KeypadCompanion.ui'
##
## Created by: Qt User Interface Compiler version 6.7.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractButton, QApplication, QComboBox, QDialog,
    QDialogButtonBox, QGridLayout, QLabel, QPushButton,
    QSizePolicy, QWidget)

from keybindedit import keybindEdit
import companion_assets_rc

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(600, 400)
        icon = QIcon()
        icon.addFile(u":/logo/assets/SkyMusicLogo.svg", QSize(), QIcon.Normal, QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.buttonBox = QDialogButtonBox(Dialog)
        self.buttonBox.setObjectName(u"buttonBox")
        self.buttonBox.setGeometry(QRect(15, 350, 571, 41))
        self.buttonBox.setOrientation(Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QDialogButtonBox.StandardButton.Cancel|QDialogButtonBox.StandardButton.Discard|QDialogButtonBox.StandardButton.Help|QDialogButtonBox.StandardButton.Ok|QDialogButtonBox.StandardButton.Open|QDialogButtonBox.StandardButton.Save)
        self.buttonBox.setCenterButtons(False)
        self.gridLayoutWidget = QWidget(Dialog)
        self.gridLayoutWidget.setObjectName(u"gridLayoutWidget")
        self.gridLayoutWidget.setGeometry(QRect(100, 110, 391, 231))
        self.gridLayout = QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.lineEdit_05 = keybindEdit(self.gridLayoutWidget)
        self.lineEdit_05.setObjectName(u"lineEdit_05")
        sizePolicy = QSizePolicy(QSizePolicy.Policy.MinimumExpanding, QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_05.sizePolicy().hasHeightForWidth())
        self.lineEdit_05.setSizePolicy(sizePolicy)
        self.lineEdit_05.setMinimumSize(QSize(72, 72))
        font = QFont()
        font.setPointSize(15)
        self.lineEdit_05.setFont(font)
        self.lineEdit_05.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.lineEdit_05.setStyleSheet(u"image: url(:/keyIcons/assets/skyMusic_circle.svg);")
        self.lineEdit_05.setText(u"")
        self.lineEdit_05.setMaxLength(1)
        self.lineEdit_05.setFrame(False)
        self.lineEdit_05.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_05.setCursorMoveStyle(Qt.CursorMoveStyle.VisualMoveStyle)

        self.gridLayout.addWidget(self.lineEdit_05, 0, 9, 1, 1, Qt.AlignmentFlag.AlignHCenter|Qt.AlignmentFlag.AlignVCenter)

        self.lineEdit_04 = keybindEdit(self.gridLayoutWidget)
        self.lineEdit_04.setObjectName(u"lineEdit_04")
        sizePolicy.setHeightForWidth(self.lineEdit_04.sizePolicy().hasHeightForWidth())
        self.lineEdit_04.setSizePolicy(sizePolicy)
        self.lineEdit_04.setMinimumSize(QSize(72, 72))
        self.lineEdit_04.setFont(font)
        self.lineEdit_04.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.lineEdit_04.setAutoFillBackground(False)
        self.lineEdit_04.setStyleSheet(u"image: url(:/keyIcons/assets/skyMusic_square.svg);")
        self.lineEdit_04.setText(u"")
        self.lineEdit_04.setMaxLength(1)
        self.lineEdit_04.setFrame(False)
        self.lineEdit_04.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_04.setCursorMoveStyle(Qt.CursorMoveStyle.VisualMoveStyle)

        self.gridLayout.addWidget(self.lineEdit_04, 0, 8, 1, 1, Qt.AlignmentFlag.AlignHCenter|Qt.AlignmentFlag.AlignVCenter)

        self.lineEdit_01 = keybindEdit(self.gridLayoutWidget)
        self.lineEdit_01.setObjectName(u"lineEdit_01")
        sizePolicy.setHeightForWidth(self.lineEdit_01.sizePolicy().hasHeightForWidth())
        self.lineEdit_01.setSizePolicy(sizePolicy)
        self.lineEdit_01.setMinimumSize(QSize(72, 72))
        self.lineEdit_01.setFont(font)
        self.lineEdit_01.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.lineEdit_01.setStyleSheet(u"image: url(:/keyIcons/assets/skyMusic_both.svg);")
        self.lineEdit_01.setText(u"")
        self.lineEdit_01.setMaxLength(1)
        self.lineEdit_01.setFrame(False)
        self.lineEdit_01.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_01.setCursorMoveStyle(Qt.CursorMoveStyle.VisualMoveStyle)

        self.gridLayout.addWidget(self.lineEdit_01, 0, 5, 1, 1, Qt.AlignmentFlag.AlignHCenter|Qt.AlignmentFlag.AlignVCenter)

        self.lineEdit_09 = keybindEdit(self.gridLayoutWidget)
        self.lineEdit_09.setObjectName(u"lineEdit_09")
        sizePolicy.setHeightForWidth(self.lineEdit_09.sizePolicy().hasHeightForWidth())
        self.lineEdit_09.setSizePolicy(sizePolicy)
        self.lineEdit_09.setMinimumSize(QSize(72, 72))
        self.lineEdit_09.setFont(font)
        self.lineEdit_09.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.lineEdit_09.setAutoFillBackground(False)
        self.lineEdit_09.setStyleSheet(u"image: url(:/keyIcons/assets/skyMusic_square.svg);")
        self.lineEdit_09.setText(u"")
        self.lineEdit_09.setMaxLength(1)
        self.lineEdit_09.setFrame(False)
        self.lineEdit_09.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_09.setCursorMoveStyle(Qt.CursorMoveStyle.VisualMoveStyle)

        self.gridLayout.addWidget(self.lineEdit_09, 1, 8, 1, 1, Qt.AlignmentFlag.AlignHCenter|Qt.AlignmentFlag.AlignVCenter)

        self.lineEdit_03 = keybindEdit(self.gridLayoutWidget)
        self.lineEdit_03.setObjectName(u"lineEdit_03")
        sizePolicy.setHeightForWidth(self.lineEdit_03.sizePolicy().hasHeightForWidth())
        self.lineEdit_03.setSizePolicy(sizePolicy)
        self.lineEdit_03.setMinimumSize(QSize(72, 72))
        self.lineEdit_03.setFont(font)
        self.lineEdit_03.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.lineEdit_03.setStyleSheet(u"image: url(:/keyIcons/assets/skyMusic_circle.svg);")
        self.lineEdit_03.setText(u"")
        self.lineEdit_03.setMaxLength(1)
        self.lineEdit_03.setFrame(False)
        self.lineEdit_03.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_03.setCursorMoveStyle(Qt.CursorMoveStyle.VisualMoveStyle)

        self.gridLayout.addWidget(self.lineEdit_03, 0, 7, 1, 1, Qt.AlignmentFlag.AlignHCenter|Qt.AlignmentFlag.AlignVCenter)

        self.lineEdit_10 = keybindEdit(self.gridLayoutWidget)
        self.lineEdit_10.setObjectName(u"lineEdit_10")
        sizePolicy.setHeightForWidth(self.lineEdit_10.sizePolicy().hasHeightForWidth())
        self.lineEdit_10.setSizePolicy(sizePolicy)
        self.lineEdit_10.setMinimumSize(QSize(72, 72))
        self.lineEdit_10.setFont(font)
        self.lineEdit_10.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.lineEdit_10.setStyleSheet(u"image: url(:/keyIcons/assets/skyMusic_circle.svg);")
        self.lineEdit_10.setText(u"")
        self.lineEdit_10.setMaxLength(1)
        self.lineEdit_10.setFrame(False)
        self.lineEdit_10.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_10.setCursorMoveStyle(Qt.CursorMoveStyle.VisualMoveStyle)

        self.gridLayout.addWidget(self.lineEdit_10, 1, 9, 1, 1, Qt.AlignmentFlag.AlignHCenter|Qt.AlignmentFlag.AlignVCenter)

        self.lineEdit_02 = keybindEdit(self.gridLayoutWidget)
        self.lineEdit_02.setObjectName(u"lineEdit_02")
        sizePolicy.setHeightForWidth(self.lineEdit_02.sizePolicy().hasHeightForWidth())
        self.lineEdit_02.setSizePolicy(sizePolicy)
        self.lineEdit_02.setMinimumSize(QSize(72, 72))
        self.lineEdit_02.setFont(font)
        self.lineEdit_02.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.lineEdit_02.setAutoFillBackground(False)
        self.lineEdit_02.setStyleSheet(u"image: url(:/keyIcons/assets/skyMusic_square.svg);")
        self.lineEdit_02.setText(u"")
        self.lineEdit_02.setMaxLength(1)
        self.lineEdit_02.setFrame(False)
        self.lineEdit_02.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_02.setCursorMoveStyle(Qt.CursorMoveStyle.VisualMoveStyle)

        self.gridLayout.addWidget(self.lineEdit_02, 0, 6, 1, 1, Qt.AlignmentFlag.AlignHCenter|Qt.AlignmentFlag.AlignVCenter)

        self.lineEdit_06 = keybindEdit(self.gridLayoutWidget)
        self.lineEdit_06.setObjectName(u"lineEdit_06")
        sizePolicy.setHeightForWidth(self.lineEdit_06.sizePolicy().hasHeightForWidth())
        self.lineEdit_06.setSizePolicy(sizePolicy)
        self.lineEdit_06.setMinimumSize(QSize(72, 72))
        self.lineEdit_06.setFont(font)
        self.lineEdit_06.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.lineEdit_06.setStyleSheet(u"image: url(:/keyIcons/assets/skyMusic_circle.svg);")
        self.lineEdit_06.setText(u"")
        self.lineEdit_06.setMaxLength(1)
        self.lineEdit_06.setFrame(False)
        self.lineEdit_06.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_06.setCursorMoveStyle(Qt.CursorMoveStyle.VisualMoveStyle)

        self.gridLayout.addWidget(self.lineEdit_06, 1, 5, 1, 1, Qt.AlignmentFlag.AlignHCenter|Qt.AlignmentFlag.AlignVCenter)

        self.lineEdit_08 = keybindEdit(self.gridLayoutWidget)
        self.lineEdit_08.setObjectName(u"lineEdit_08")
        sizePolicy.setHeightForWidth(self.lineEdit_08.sizePolicy().hasHeightForWidth())
        self.lineEdit_08.setSizePolicy(sizePolicy)
        self.lineEdit_08.setMinimumSize(QSize(72, 72))
        self.lineEdit_08.setFont(font)
        self.lineEdit_08.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.lineEdit_08.setStyleSheet(u"image: url(:/keyIcons/assets/skyMusic_both.svg);")
        self.lineEdit_08.setText(u"")
        self.lineEdit_08.setMaxLength(1)
        self.lineEdit_08.setFrame(False)
        self.lineEdit_08.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_08.setCursorMoveStyle(Qt.CursorMoveStyle.VisualMoveStyle)

        self.gridLayout.addWidget(self.lineEdit_08, 1, 7, 1, 1, Qt.AlignmentFlag.AlignHCenter|Qt.AlignmentFlag.AlignVCenter)

        self.lineEdit_07 = keybindEdit(self.gridLayoutWidget)
        self.lineEdit_07.setObjectName(u"lineEdit_07")
        sizePolicy.setHeightForWidth(self.lineEdit_07.sizePolicy().hasHeightForWidth())
        self.lineEdit_07.setSizePolicy(sizePolicy)
        self.lineEdit_07.setMinimumSize(QSize(72, 72))
        self.lineEdit_07.setFont(font)
        self.lineEdit_07.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.lineEdit_07.setAutoFillBackground(False)
        self.lineEdit_07.setStyleSheet(u"image: url(:/keyIcons/assets/skyMusic_square.svg);")
        self.lineEdit_07.setText(u"")
        self.lineEdit_07.setMaxLength(1)
        self.lineEdit_07.setFrame(False)
        self.lineEdit_07.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_07.setCursorMoveStyle(Qt.CursorMoveStyle.VisualMoveStyle)

        self.gridLayout.addWidget(self.lineEdit_07, 1, 6, 1, 1, Qt.AlignmentFlag.AlignHCenter|Qt.AlignmentFlag.AlignVCenter)

        self.lineEdit_11 = keybindEdit(self.gridLayoutWidget)
        self.lineEdit_11.setObjectName(u"lineEdit_11")
        sizePolicy.setHeightForWidth(self.lineEdit_11.sizePolicy().hasHeightForWidth())
        self.lineEdit_11.setSizePolicy(sizePolicy)
        self.lineEdit_11.setMinimumSize(QSize(72, 72))
        self.lineEdit_11.setFont(font)
        self.lineEdit_11.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.lineEdit_11.setStyleSheet(u"image: url(:/keyIcons/assets/skyMusic_circle.svg);")
        self.lineEdit_11.setText(u"")
        self.lineEdit_11.setMaxLength(1)
        self.lineEdit_11.setFrame(False)
        self.lineEdit_11.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_11.setCursorMoveStyle(Qt.CursorMoveStyle.VisualMoveStyle)

        self.gridLayout.addWidget(self.lineEdit_11, 2, 5, 1, 1, Qt.AlignmentFlag.AlignHCenter|Qt.AlignmentFlag.AlignVCenter)

        self.lineEdit_12 = keybindEdit(self.gridLayoutWidget)
        self.lineEdit_12.setObjectName(u"lineEdit_12")
        sizePolicy.setHeightForWidth(self.lineEdit_12.sizePolicy().hasHeightForWidth())
        self.lineEdit_12.setSizePolicy(sizePolicy)
        self.lineEdit_12.setMinimumSize(QSize(72, 72))
        self.lineEdit_12.setFont(font)
        self.lineEdit_12.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.lineEdit_12.setAutoFillBackground(False)
        self.lineEdit_12.setStyleSheet(u"image: url(:/keyIcons/assets/skyMusic_square.svg);")
        self.lineEdit_12.setText(u"")
        self.lineEdit_12.setMaxLength(1)
        self.lineEdit_12.setFrame(False)
        self.lineEdit_12.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_12.setCursorMoveStyle(Qt.CursorMoveStyle.VisualMoveStyle)

        self.gridLayout.addWidget(self.lineEdit_12, 2, 6, 1, 1, Qt.AlignmentFlag.AlignHCenter|Qt.AlignmentFlag.AlignVCenter)

        self.lineEdit_13 = keybindEdit(self.gridLayoutWidget)
        self.lineEdit_13.setObjectName(u"lineEdit_13")
        sizePolicy.setHeightForWidth(self.lineEdit_13.sizePolicy().hasHeightForWidth())
        self.lineEdit_13.setSizePolicy(sizePolicy)
        self.lineEdit_13.setMinimumSize(QSize(72, 72))
        self.lineEdit_13.setFont(font)
        self.lineEdit_13.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.lineEdit_13.setStyleSheet(u"image: url(:/keyIcons/assets/skyMusic_circle.svg);")
        self.lineEdit_13.setText(u"")
        self.lineEdit_13.setMaxLength(1)
        self.lineEdit_13.setFrame(False)
        self.lineEdit_13.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_13.setCursorMoveStyle(Qt.CursorMoveStyle.VisualMoveStyle)

        self.gridLayout.addWidget(self.lineEdit_13, 2, 7, 1, 1, Qt.AlignmentFlag.AlignHCenter|Qt.AlignmentFlag.AlignVCenter)

        self.lineEdit_14 = keybindEdit(self.gridLayoutWidget)
        self.lineEdit_14.setObjectName(u"lineEdit_14")
        sizePolicy.setHeightForWidth(self.lineEdit_14.sizePolicy().hasHeightForWidth())
        self.lineEdit_14.setSizePolicy(sizePolicy)
        self.lineEdit_14.setMinimumSize(QSize(72, 72))
        self.lineEdit_14.setFont(font)
        self.lineEdit_14.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.lineEdit_14.setAutoFillBackground(False)
        self.lineEdit_14.setStyleSheet(u"image: url(:/keyIcons/assets/skyMusic_square.svg);")
        self.lineEdit_14.setText(u"")
        self.lineEdit_14.setMaxLength(1)
        self.lineEdit_14.setFrame(False)
        self.lineEdit_14.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_14.setCursorMoveStyle(Qt.CursorMoveStyle.VisualMoveStyle)

        self.gridLayout.addWidget(self.lineEdit_14, 2, 8, 1, 1, Qt.AlignmentFlag.AlignHCenter|Qt.AlignmentFlag.AlignVCenter)

        self.lineEdit_15 = keybindEdit(self.gridLayoutWidget)
        self.lineEdit_15.setObjectName(u"lineEdit_15")
        sizePolicy.setHeightForWidth(self.lineEdit_15.sizePolicy().hasHeightForWidth())
        self.lineEdit_15.setSizePolicy(sizePolicy)
        self.lineEdit_15.setMinimumSize(QSize(72, 72))
        self.lineEdit_15.setFont(font)
        self.lineEdit_15.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.lineEdit_15.setStyleSheet(u"image: url(:/keyIcons/assets/skyMusic_both.svg);")
        self.lineEdit_15.setText(u"")
        self.lineEdit_15.setMaxLength(1)
        self.lineEdit_15.setFrame(False)
        self.lineEdit_15.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_15.setCursorMoveStyle(Qt.CursorMoveStyle.VisualMoveStyle)

        self.gridLayout.addWidget(self.lineEdit_15, 2, 9, 1, 1, Qt.AlignmentFlag.AlignHCenter|Qt.AlignmentFlag.AlignVCenter)

        self.skyLogo = QLabel(Dialog)
        self.skyLogo.setObjectName(u"skyLogo")
        self.skyLogo.setGeometry(QRect(0, 5, 91, 81))
        self.skyLogo.setStyleSheet(u"image: url(:/logo/assets/SkyLogo.svg);")
        self.layoutWidget = QWidget(Dialog)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(130, 20, 389, 58))
        self.gridLayout_2 = QGridLayout(self.layoutWidget)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.deviceRefresh = QPushButton(self.layoutWidget)
        self.deviceRefresh.setObjectName(u"deviceRefresh")
        self.deviceRefresh.setMinimumSize(QSize(24, 24))
        icon1 = QIcon()
        icon1.addFile(u":/icons/assets/view-refresh.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.deviceRefresh.setIcon(icon1)

        self.gridLayout_2.addWidget(self.deviceRefresh, 0, 2, 1, 1, Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)

        self.label_mapMode = QLabel(self.layoutWidget)
        self.label_mapMode.setObjectName(u"label_mapMode")

        self.gridLayout_2.addWidget(self.label_mapMode, 1, 0, 1, 1, Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignVCenter)

        self.device = QComboBox(self.layoutWidget)
        self.device.setObjectName(u"device")
        self.device.setMinimumSize(QSize(125, 0))

        self.gridLayout_2.addWidget(self.device, 0, 1, 1, 1, Qt.AlignmentFlag.AlignHCenter|Qt.AlignmentFlag.AlignVCenter)

        self.keypadMode = QComboBox(self.layoutWidget)
        self.keypadMode.setObjectName(u"keypadMode")
        self.keypadMode.setEnabled(False)
        self.keypadMode.setMinimumSize(QSize(125, 0))

        self.gridLayout_2.addWidget(self.keypadMode, 1, 1, 1, 1, Qt.AlignmentFlag.AlignHCenter|Qt.AlignmentFlag.AlignVCenter)

        self.label_device = QLabel(self.layoutWidget)
        self.label_device.setObjectName(u"label_device")

        self.gridLayout_2.addWidget(self.label_device, 0, 0, 1, 1, Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignVCenter)

        self.validLabel = QLabel(self.layoutWidget)
        self.validLabel.setObjectName(u"validLabel")
        self.validLabel.setEnabled(True)
        self.validLabel.setCursor(QCursor(Qt.ArrowCursor))
        self.validLabel.setAutoFillBackground(False)
        self.validLabel.setStyleSheet(u"color: rgb(255, 0, 0);")
        self.validLabel.setLineWidth(1)

        self.gridLayout_2.addWidget(self.validLabel, 0, 3, 1, 1, Qt.AlignmentFlag.AlignHCenter|Qt.AlignmentFlag.AlignVCenter)

        QWidget.setTabOrder(self.device, self.keypadMode)
        QWidget.setTabOrder(self.keypadMode, self.lineEdit_01)
        QWidget.setTabOrder(self.lineEdit_01, self.lineEdit_02)
        QWidget.setTabOrder(self.lineEdit_02, self.lineEdit_03)
        QWidget.setTabOrder(self.lineEdit_03, self.lineEdit_04)
        QWidget.setTabOrder(self.lineEdit_04, self.lineEdit_05)
        QWidget.setTabOrder(self.lineEdit_05, self.lineEdit_06)
        QWidget.setTabOrder(self.lineEdit_06, self.lineEdit_07)
        QWidget.setTabOrder(self.lineEdit_07, self.lineEdit_08)
        QWidget.setTabOrder(self.lineEdit_08, self.lineEdit_09)
        QWidget.setTabOrder(self.lineEdit_09, self.lineEdit_10)
        QWidget.setTabOrder(self.lineEdit_10, self.lineEdit_11)
        QWidget.setTabOrder(self.lineEdit_11, self.lineEdit_12)
        QWidget.setTabOrder(self.lineEdit_12, self.lineEdit_13)
        QWidget.setTabOrder(self.lineEdit_13, self.lineEdit_14)
        QWidget.setTabOrder(self.lineEdit_14, self.lineEdit_15)

        self.retranslateUi(Dialog)

        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"Sky Keypad Companion", None))
        self.skyLogo.setText("")
        self.deviceRefresh.setText("")
        self.label_mapMode.setText(QCoreApplication.translate("Dialog", u"Keypad Mapping Mode:", None))
        self.label_device.setText(QCoreApplication.translate("Dialog", u"Device:", None))
        self.validLabel.setText(QCoreApplication.translate("Dialog", u"Invalid Device!", None))
    # retranslateUi

